/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InternalRouteImport } from './routes/internal'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as PolicyIssuedRouteImport } from './routes/policy.issued'
import { Route as PlansIdRouteImport } from './routes/plans.$id'
import { Route as OnboardingAnalyzingRouteImport } from './routes/onboarding.analyzing'
import { Route as InternalUnderwritingRouteImport } from './routes/internal.underwriting'
import { Route as InternalClaimsRouteImport } from './routes/internal.claims'
import { Route as InternalAuditRouteImport } from './routes/internal.audit'
import { Route as InternalAdminRouteImport } from './routes/internal.admin'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardPoliciesRouteImport } from './routes/dashboard.policies'
import { Route as DashboardDocumentsRouteImport } from './routes/dashboard.documents'
import { Route as DashboardAssistantRouteImport } from './routes/dashboard.assistant'
import { Route as DashboardClaimsNewRouteImport } from './routes/dashboard.claims.new'

const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalRoute = InternalRouteImport.update({
  id: '/internal',
  path: '/internal',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const PolicyIssuedRoute = PolicyIssuedRouteImport.update({
  id: '/policy/issued',
  path: '/policy/issued',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansIdRoute = PlansIdRouteImport.update({
  id: '/plans/$id',
  path: '/plans/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingAnalyzingRoute = OnboardingAnalyzingRouteImport.update({
  id: '/onboarding/analyzing',
  path: '/onboarding/analyzing',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalUnderwritingRoute = InternalUnderwritingRouteImport.update({
  id: '/underwriting',
  path: '/underwriting',
  getParentRoute: () => InternalRoute,
} as any)
const InternalClaimsRoute = InternalClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => InternalRoute,
} as any)
const InternalAuditRoute = InternalAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => InternalRoute,
} as any)
const InternalAdminRoute = InternalAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => InternalRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPoliciesRoute = DashboardPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDocumentsRoute = DashboardDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAssistantRoute = DashboardAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClaimsNewRoute = DashboardClaimsNewRouteImport.update({
  id: '/claims/new',
  path: '/claims/new',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/internal': typeof InternalRouteWithChildren
  '/login': typeof LoginRoute
  '/recommendations': typeof RecommendationsRoute
  '/signup': typeof SignupRoute
  '/verification': typeof VerificationRoute
  '/dashboard/assistant': typeof DashboardAssistantRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/policies': typeof DashboardPoliciesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/internal/admin': typeof InternalAdminRoute
  '/internal/audit': typeof InternalAuditRoute
  '/internal/claims': typeof InternalClaimsRoute
  '/internal/underwriting': typeof InternalUnderwritingRoute
  '/onboarding/analyzing': typeof OnboardingAnalyzingRoute
  '/plans/$id': typeof PlansIdRoute
  '/policy/issued': typeof PolicyIssuedRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/dashboard/claims/new': typeof DashboardClaimsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/internal': typeof InternalRouteWithChildren
  '/login': typeof LoginRoute
  '/recommendations': typeof RecommendationsRoute
  '/signup': typeof SignupRoute
  '/verification': typeof VerificationRoute
  '/dashboard/assistant': typeof DashboardAssistantRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/policies': typeof DashboardPoliciesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/internal/admin': typeof InternalAdminRoute
  '/internal/audit': typeof InternalAuditRoute
  '/internal/claims': typeof InternalClaimsRoute
  '/internal/underwriting': typeof InternalUnderwritingRoute
  '/onboarding/analyzing': typeof OnboardingAnalyzingRoute
  '/plans/$id': typeof PlansIdRoute
  '/policy/issued': typeof PolicyIssuedRoute
  '/dashboard': typeof DashboardIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/dashboard/claims/new': typeof DashboardClaimsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/internal': typeof InternalRouteWithChildren
  '/login': typeof LoginRoute
  '/recommendations': typeof RecommendationsRoute
  '/signup': typeof SignupRoute
  '/verification': typeof VerificationRoute
  '/dashboard/assistant': typeof DashboardAssistantRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/policies': typeof DashboardPoliciesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/internal/admin': typeof InternalAdminRoute
  '/internal/audit': typeof InternalAuditRoute
  '/internal/claims': typeof InternalClaimsRoute
  '/internal/underwriting': typeof InternalUnderwritingRoute
  '/onboarding/analyzing': typeof OnboardingAnalyzingRoute
  '/plans/$id': typeof PlansIdRoute
  '/policy/issued': typeof PolicyIssuedRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/dashboard/claims/new': typeof DashboardClaimsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/compare'
    | '/dashboard'
    | '/internal'
    | '/login'
    | '/recommendations'
    | '/signup'
    | '/verification'
    | '/dashboard/assistant'
    | '/dashboard/documents'
    | '/dashboard/policies'
    | '/dashboard/settings'
    | '/internal/admin'
    | '/internal/audit'
    | '/internal/claims'
    | '/internal/underwriting'
    | '/onboarding/analyzing'
    | '/plans/$id'
    | '/policy/issued'
    | '/dashboard/'
    | '/onboarding/'
    | '/dashboard/claims/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/compare'
    | '/internal'
    | '/login'
    | '/recommendations'
    | '/signup'
    | '/verification'
    | '/dashboard/assistant'
    | '/dashboard/documents'
    | '/dashboard/policies'
    | '/dashboard/settings'
    | '/internal/admin'
    | '/internal/audit'
    | '/internal/claims'
    | '/internal/underwriting'
    | '/onboarding/analyzing'
    | '/plans/$id'
    | '/policy/issued'
    | '/dashboard'
    | '/onboarding'
    | '/dashboard/claims/new'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/compare'
    | '/dashboard'
    | '/internal'
    | '/login'
    | '/recommendations'
    | '/signup'
    | '/verification'
    | '/dashboard/assistant'
    | '/dashboard/documents'
    | '/dashboard/policies'
    | '/dashboard/settings'
    | '/internal/admin'
    | '/internal/audit'
    | '/internal/claims'
    | '/internal/underwriting'
    | '/onboarding/analyzing'
    | '/plans/$id'
    | '/policy/issued'
    | '/dashboard/'
    | '/onboarding/'
    | '/dashboard/claims/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  CompareRoute: typeof CompareRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  InternalRoute: typeof InternalRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecommendationsRoute: typeof RecommendationsRoute
  SignupRoute: typeof SignupRoute
  VerificationRoute: typeof VerificationRoute
  OnboardingAnalyzingRoute: typeof OnboardingAnalyzingRoute
  PlansIdRoute: typeof PlansIdRoute
  PolicyIssuedRoute: typeof PolicyIssuedRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal': {
      id: '/internal'
      path: '/internal'
      fullPath: '/internal'
      preLoaderRoute: typeof InternalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/policy/issued': {
      id: '/policy/issued'
      path: '/policy/issued'
      fullPath: '/policy/issued'
      preLoaderRoute: typeof PolicyIssuedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/$id': {
      id: '/plans/$id'
      path: '/plans/$id'
      fullPath: '/plans/$id'
      preLoaderRoute: typeof PlansIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/analyzing': {
      id: '/onboarding/analyzing'
      path: '/onboarding/analyzing'
      fullPath: '/onboarding/analyzing'
      preLoaderRoute: typeof OnboardingAnalyzingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/underwriting': {
      id: '/internal/underwriting'
      path: '/underwriting'
      fullPath: '/internal/underwriting'
      preLoaderRoute: typeof InternalUnderwritingRouteImport
      parentRoute: typeof InternalRoute
    }
    '/internal/claims': {
      id: '/internal/claims'
      path: '/claims'
      fullPath: '/internal/claims'
      preLoaderRoute: typeof InternalClaimsRouteImport
      parentRoute: typeof InternalRoute
    }
    '/internal/audit': {
      id: '/internal/audit'
      path: '/audit'
      fullPath: '/internal/audit'
      preLoaderRoute: typeof InternalAuditRouteImport
      parentRoute: typeof InternalRoute
    }
    '/internal/admin': {
      id: '/internal/admin'
      path: '/admin'
      fullPath: '/internal/admin'
      preLoaderRoute: typeof InternalAdminRouteImport
      parentRoute: typeof InternalRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/policies': {
      id: '/dashboard/policies'
      path: '/policies'
      fullPath: '/dashboard/policies'
      preLoaderRoute: typeof DashboardPoliciesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/documents': {
      id: '/dashboard/documents'
      path: '/documents'
      fullPath: '/dashboard/documents'
      preLoaderRoute: typeof DashboardDocumentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/assistant': {
      id: '/dashboard/assistant'
      path: '/assistant'
      fullPath: '/dashboard/assistant'
      preLoaderRoute: typeof DashboardAssistantRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/claims/new': {
      id: '/dashboard/claims/new'
      path: '/claims/new'
      fullPath: '/dashboard/claims/new'
      preLoaderRoute: typeof DashboardClaimsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAssistantRoute: typeof DashboardAssistantRoute
  DashboardDocumentsRoute: typeof DashboardDocumentsRoute
  DashboardPoliciesRoute: typeof DashboardPoliciesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardClaimsNewRoute: typeof DashboardClaimsNewRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAssistantRoute: DashboardAssistantRoute,
  DashboardDocumentsRoute: DashboardDocumentsRoute,
  DashboardPoliciesRoute: DashboardPoliciesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardClaimsNewRoute: DashboardClaimsNewRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface InternalRouteChildren {
  InternalAdminRoute: typeof InternalAdminRoute
  InternalAuditRoute: typeof InternalAuditRoute
  InternalClaimsRoute: typeof InternalClaimsRoute
  InternalUnderwritingRoute: typeof InternalUnderwritingRoute
}

const InternalRouteChildren: InternalRouteChildren = {
  InternalAdminRoute: InternalAdminRoute,
  InternalAuditRoute: InternalAuditRoute,
  InternalClaimsRoute: InternalClaimsRoute,
  InternalUnderwritingRoute: InternalUnderwritingRoute,
}

const InternalRouteWithChildren = InternalRoute._addFileChildren(
  InternalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  CompareRoute: CompareRoute,
  DashboardRoute: DashboardRouteWithChildren,
  InternalRoute: InternalRouteWithChildren,
  LoginRoute: LoginRoute,
  RecommendationsRoute: RecommendationsRoute,
  SignupRoute: SignupRoute,
  VerificationRoute: VerificationRoute,
  OnboardingAnalyzingRoute: OnboardingAnalyzingRoute,
  PlansIdRoute: PlansIdRoute,
  PolicyIssuedRoute: PolicyIssuedRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
